"""
A module for writing audit log records with monotonic sequence numbers.
"""

import threading
from typing import Any, Dict, List


class AuditLogWriter:
    """
    Writes audit log records to a sink with monotonic sequence numbers.

    This class is thread-safe. Each call to the `write` method is an atomic
    operation that generates a unique, monotonically increasing sequence number.
    """

    def __init__(self, sink: List[Dict[str, Any]]):
        """
        Initializes the AuditLogWriter.

        The writer will append records to the provided sink. The sequence number
        for records generated by this instance will start at 1.

        Args:
            sink: A list object to which audit records will be appended.

        Raises:
            TypeError: If the provided sink is not a list.
        """
        if not isinstance(sink, list):
            raise TypeError("sink must be a list")
        self._sink = sink
        self._sequence_number = 0
        self._lock = threading.Lock()

    def write(self, actor: str, action: str) -> Dict[str, Any]:
        """
        Creates, appends, and returns an audit record.

        The method generates a new record containing the actor, action, and a
        monotonic sequence number. This record is appended to the sink provided
        during initialization.

        Args:
            actor: The identifier of the entity performing the action.
            action: A description of the action performed.

        Returns:
            A shallow copy of the created audit record. The returned dictionary
            is a distinct mutable object from the one appended to the sink,
            fulfilling the requirement that they must not be the same mutable
            object.
        """
        with self._lock:
            self._sequence_number += 1
            record = {
                "seq": self._sequence_number,
                "actor": actor,
                "action": action,
            }

            # The returned record must be a distinct object from the one
            # appended to the sink. A shallow copy is sufficient as the
            # dictionary values (int, str) are immutable.
            record_to_return = record.copy()
            self._sink.append(record)

            return record_to_return
