# -*- coding: utf-8 -*-
"""
A module for parsing and validating command-line arguments.
"""

import argparse
from typing import Dict, List, Union, NoReturn


class _RaisingArgumentParser(argparse.ArgumentParser):
    """
    An ArgumentParser that raises ValueError instead of calling sys.exit.
    """
    def error(self, message: str) -> NoReturn:
        """
        Overrides the default error-handling behavior to raise a ValueError.

        Args:
            message: The error message generated by argparse.

        Raises:
            ValueError: Always, with the provided error message.
        """
        raise ValueError(message)


def parse_cli_args(argv: List[str]) -> Dict[str, Union[str, int, bool]]:
    """
    Parses and validates command-line arguments.

    This function defines the expected command-line interface, including required
    flags, optional flags with defaults, and type/value constraints. It uses a
    custom ArgumentParser subclass to raise ValueError on parsing errors instead
    of exiting the program.

    Supported flags:
    - --input PATH: Required. Path to the input file.
    - --limit N: Optional. A positive integer limit. Defaults to 100.
    - --format VALUE: Optional. Must be "json" or "csv". Defaults to "json".
    - --dry-run: Optional. A boolean flag.

    Args:
        argv: A list of string arguments, typically from sys.argv[1:].

    Returns:
        A dictionary containing the parsed and validated arguments.
        Example:
        {
            "input": "/path/to/file",
            "limit": 50,
            "format": "csv",
            "dry_run": True
        }

    Raises:
        ValueError: If any of the following conditions are met:
                    - A required flag is missing.
                    - An unknown flag is provided.
                    - A flag that requires a value is missing its value.
                    - A flag's value is of the wrong type or not in the
                      allowed set of choices.
                    - The --limit value is not a positive integer.
    """
    parser = _RaisingArgumentParser(
        description="A secure CLI argument parser.",
        add_help=False  # Disable the default help flag to prevent sys.exit.
    )

    parser.add_argument(
        "--input",
        required=True,
        type=str,
        metavar="PATH",
        help="The path to the input file (required)."
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=100,
        metavar="N",
        help="A positive integer limit (optional, default: 100)."
    )
    parser.add_argument(
        "--format",
        default="json",
        choices=["json", "csv"],
        metavar="VALUE",
        help="The output format, 'json' or 'csv' (optional, default: 'json')."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="If set, performs a dry run without making changes."
    )

    # The overridden error() method in _RaisingArgumentParser ensures that
    # parse_args will raise ValueError on any parsing error.
    args = parser.parse_args(args=argv)

    # Perform custom validation that is not covered by argparse's basic checks.
    if args.limit <= 0:
        raise ValueError("Value for --limit must be a positive integer.")

    return {
        "input": args.input,
        "limit": args.limit,
        "format": args.format,
        "dry_run": args.dry_run,
    }
